name: DungeonCrawler
version: ${project.version}
main: me.dkflab.dungeoncrawler.DungeonCrawler
api-version: 1.17
authors: [dkflab]
softdepend: [Multiverse-Core]
description: Dungeon crawler plugin
commands:
  class:
    description: Class selector
  dungeon:
    description: Matchmaking command
  upgrade:
    description: Upgrade tools
  shop:
    description: Shop for tools
  createclass:
    description: Create a class
    permission: dungeon.admin
  balance:
    description: Check balance in emeralds
    aliases: [bal, emeralds, emerald]
  barrel:
    description: Add item to barrel
    usage: /<command> <name>
    permission: dungeon.admin
